#!/bin/sh
GREEN="\x1B[32m"
RED="\x1B[31m"
YELLOW="\x1B[33m"
RESET="\x1B[0m"

log() {
  printf "%b" "$GREEN$1$RESET\n"
}
clearline() {
  printf "                                                                                          \r"
}
sameline() {
  printf "%b" "$GREEN$1$RESET\r"
}
warn() {
  printf "%b" "$RED$1$RESET\n"
}
error() {
  printf "%b" "$RED$1$RESET\n" exit 1
}

BRANCH=$(git rev-parse --abbrev-ref HEAD)

# check if remote branch exists
REMOTE=origin
REMOTE_BRANCH=$REMOTE/$BRANCH
git branch -a | grep $REMOTE_BRANCH
if [ $? = 1 ]; then
  REMOTE_BRANCH=$REMOTE/master
fi

COMMITED_FILES=$(git diff --name-only --diff-filter=ACM --name-only $REMOTE_BRANCH..$BRANCH | grep ".jsx\{0,1\}$")

if [[ "$COMMITED_FILES" = "" ]]; then
  log 'No files to lint.'
  exit 0
fi

PASS=true

log 'Linting committed files...\n'

for FILE in $COMMITED_FILES
do
  if [ -f ./node_modules/.bin/eslint_d ]; then
    # quiet: Report errors only so that the fact that .eslintignore is being used and
    # thus triggers a warning (-.-) doesn't fail the build.
    ./node_modules/.bin/eslint_d --cache --max-warnings 0 --quiet "$FILE" &>/dev/null
  else
    ./node_modules/.bin/eslint --cache --max-warnings 0 --quiet "$FILE" &>/dev/null
  fi

  if [[ "$?" == 0 ]]; then
    clearline
    sameline "  ✓ $FILE"
  else
    clearline
    warn "  ✘ $FILE"
    PASS=false
  fi
done



set -x
if [ "$PASS" = false ]; then
  error "\nPush failed: The commits contain files that don't pass eslint."
  exit 1
else
	if [ -f ./.flowconfig ]; then
		log '\nESLint successful, now running Flow...\n'
		flow
	else
		log '\nESLint successful.\n'
	fi
fi
